In [5]:
"""
Yahoo Finance 캘린더 데이터 로드 예제 (Jupyter Notebook 버전)
"""

import os
import sys

# 현재 노트북 파일의 디렉토리 경로 가져오기
notebook_dir = os.getcwd()
# 프로젝트 루트 디렉토리 (현재 디렉토리의 상위 디렉토리)
project_root = os.path.dirname(notebook_dir)

# 프로젝트 루트 디렉토리를 파이썬 경로에 추가
if project_root not in sys.path:
    sys.path.append(project_root)

from yfinance_calendar.utils.data_loader import CalendarDataLoader

# 데이터 디렉토리 설정
data_dir = os.path.join(project_root, 'output')

# 데이터 로더 초기화
loader = CalendarDataLoader(data_dir)

try:
    # 모든 캘린더 데이터 로드
    calendar_data = loader.load_all_calendar_data()
    
    # 각 데이터프레임 출력
    for calendar_type, df in calendar_data.items():
        print(f"\n{calendar_type.upper()} 데이터:")
        print(f"행 수: {len(df)}")
        print(f"컬럼: {', '.join(df.columns)}")
        print("\n처음 5개 행:")
        display(df.head())
        print("\n" + "="*80)
    
    # 데이터프레임 활용 예시
    
    # 1. Earnings 데이터 분석
    earnings_df = calendar_data['earnings']
    if not earnings_df.empty:
        print("\n실적 발표 통계:")
        print(f"총 기업 수: {len(earnings_df['symbol'].unique())}")
        print("\nEPS 추정치가 있는 기업:")
        display(earnings_df[earnings_df['eps_estimate'].notna()][['symbol', 'company', 'eps_estimate']])
    
    # 2. Economic 데이터 분석
    economic_df = calendar_data['economic']
    if not economic_df.empty:
        print("\n경제 지표 통계:")
        print("\n국가별 이벤트 수:")
        display(economic_df['country'].value_counts().head())
        
    # 3. IPO 데이터 분석
    ipo_df = calendar_data['ipo']
    if not ipo_df.empty:
        print("\nIPO 통계:")
        print("\n거래소별 IPO 수:")
        display(ipo_df['exchange'].value_counts())
    
    # 4. Splits 데이터 분석
    splits_df = calendar_data['splits']
    if not splits_df.empty:
        print("\n주식 분할 통계:")
        print(f"총 분할 건수: {len(splits_df)}")
        print("\n옵션 가능 여부:")
        display(splits_df['optionable'].value_counts())

except Exception as e:
    print(f"데이터 로드 중 오류 발생: {str(e)}")

EARNINGS 데이터:
행 수: 333
컬럼: symbol, company, event_name, date, call_time, eps_estimate, reported_eps, surprise

처음 5개 행:

,symbol,company,event_name,date,call_time,eps_estimate,reported_eps,surprise
0,ALPP,Alpine 4 Holdings Inc,Q1 2024 Earnings Release,2025-03-10,AMC,None,None,None
1,IAUX,I-80 Gold Corp,Q4 2024 Earnings Release,2025-03-10,AMC,None,None,None
2,AGZNF,Aegean Airlines SA,Full Year 2024 Earnings Release,2025-03-10,AMC,None,None,None
3,ASAN,Asana Inc,Q4 2025 Earnings Release,2025-03-10,AMC,None,None,None
4,FUVV,Arcimoto Inc,Q2 2024 Earnings Release,2025-03-10,TAS,None,None,None

================================================================================

ECONOMIC 데이터:
행 수: 73
컬럼: event, country, date, event_time, event_for, actual, market_expectation, prior, revised_from

처음 5개 행:

,event,country,date,event_time,event_for,actual,market_expectation,prior,revised_from
0,Motorbike Sales YY*,ID,2025-03-10,4:00 AM UTC,Feb,4.04,None,-6,None
1,Coincident Index*,JP,2025-03-10,5:00 AM UTC,Jan,0.1,None,1.4,1
2,Leading Indicator*,JP,2025-03-10,5:00 AM UTC,Jan,0.1,None,0.5,None
3,Manufacturing Output MM *,NL,2025-03-10,5:30 AM UTC,Jan,1,None,-1,-0.8
4,Industry Output YY *,FI,2025-03-10,6:00 AM UTC,Jan,0.5,None,1.6,1.5

================================================================================

IPO 데이터:
행 수: 1
컬럼: symbol, company, exchange, date, ipo_date, price_range, price, currency, shares, actions

처음 5개 행:

,symbol,company,exchange,date,ipo_date,price_range,price,currency,shares,actions
0,603124.SS,Jiangxi Jiangnan New Material,Shanghai,2025-03-10,"Jun 15, 2022",None,None,CNY,None,Expected

================================================================================

SPLITS 데이터:
행 수: 26
컬럼: symbol, company, date, payable_on, optionable, ratio

처음 5개 행:

,symbol,company,date,payable_on,optionable,ratio
0,DAIKF,I-Pex Inc,2025-03-10,"Mar 10, 2025",N,1831275.00 - 1.00
1,CLOV.KA,Clover Pakistan Ltd,2025-03-10,"Mar 10, 2025",N,4.00 - 5.00
2,AIRLINK.KA,Air Link Communication Ltd,2025-03-10,"Mar 10, 2025",N,1.00 - 5.00
3,P99.SG,CodeLab Capital AS,2025-03-10,"Mar 10, 2025",N,50.00 - 1.00
4,INEN.SG,Indigo Exploration Inc,2025-03-10,"Mar 10, 2025",N,2.00 - 1.00

================================================================================

실적 발표 통계:
총 기업 수: 333

EPS 추정치가 있는 기업:

    symbol                              company eps_estimate
5     ASPS    Altisource Portfolio Solutions SA        -0.27
10     BRT                  BRT Apartments Corp        -0.12
28    ADCT                  ADC Therapeutics SA        -0.38
34    APLT             Applied Therapeutics Inc        -0.15
39    ALGS              Aligos Therapeutics Inc        -2.63
45    ABUS               Arbutus Biopharma Corp        -0.08
52    LOAN         Manhattan Bridge Capital Inc         0.12
53    MBIO                      Mustang Bio Inc        -0.16
60    GBIO                    Generation Bio Co        -0.31
65    SANA               Sana Biotechnology Inc        -0.22
72    CHRS              Coherus BioSciences Inc         -0.1
80    BNTX                          BioNTech SE         0.93
88    CRMD                         CorMedix Inc         0.05
101   GLRE            Greenlight Capital Re Ltd         0.59
102   DRIO                     DarioHealth Corp        -0.24
103   CEPU                    Central Puerto SA         0.03
121   GECC               Great Elm Capital Corp         0.37
130   GORO                   Gold Resource Corp        -0.05
132   CRBP  Corbus Pharmaceuticals Holdings Inc        -1.02
133   CVGI         Commercial Vehicle Group Inc         0.04
142   MKFG              Markforged Holding Corp        -0.33
143   CMRX                         Chimerix Inc        -0.26
144   LOGC                     ContextLogic Inc        -0.01
149    FNV                   Franco-Nevada Corp          0.9
150    RDW                         Redwire Corp        -0.14
152   XOMA                    XOMA Royalty Corp        -0.28
164   DOUG                  Douglas Elliman Inc        -0.06
166   DWTX             Dogwood Therapeutics Inc        -1.36
184     SD                 SandRidge Energy Inc         0.48
189    HPK                  Highpeak Energy Inc         0.15
192    FTK                Flotek Industries Inc         0.09
193   FENC           Fennec Pharmaceuticals Inc         0.02
201   STKS            One Group Hospitality Inc         0.22
204   GAIA                             Gaia Inc        -0.05
210    MRC                       MRC Global Inc         0.13
214   GEVO                             Gevo Inc        -0.06
215   GLTO                          Galecto Inc        -3.41
230    VMD                Viemed Healthcare Inc         0.08
231   NCSM          NCS Multistage Holdings Inc         0.83
234    LMB                 Limbach Holdings Inc         0.84
242    SST                          System1 Inc        -0.23
245   PRLD             Prelude Therapeutics Inc        -0.48
248  NUMIF                 Numinus Wellness Inc        -0.01
265   UPLD                  Upland Software Inc         0.19
269   PHUN                         Phunware Inc        -0.25
274   TBRG                        Trubridge Inc         0.29
286   INZY                   Inozyme Pharma Inc        -0.42
287   TACT            TransAct Technologies Inc        -0.09
289   MYPS                      Playstudios Inc        -0.04
291   LPCN                         Lipocine Inc        -0.26
293   METC                 Ramaco Resources Inc         0.42
298   PRPL                Purple Innovation Inc        -0.14
301   LFMD                           LifeMD Inc        -0.04
302    MYO                            Myomo Inc        -0.02
306   VCSA                           Vacasa Inc        -3.24
311   PRFX                       PainReform Ltd        -4.74
322   URGN                    Urogen Pharma Ltd        -0.69
325   PRQR                ProQR Therapeutics NV         -0.1

경제 지표 통계:

국가별 이벤트 수:

country
JP    10
NO     5
DE     4
ID     4
GR     4
Name: count, dtype: int64

IPO 통계:

거래소별 IPO 수:

exchange
Shanghai    1
Name: count, dtype: int64

주식 분할 통계:
총 분할 건수: 26

옵션 가능 여부:

optionable
N    26
Name: count, dtype: int64

## 데이터 분석 예시

위에서 로드한 데이터프레임을 사용하여 추가 분석을 수행할 수 있습니다:

In [8]:
earnings_df.to_csv("2025-03-10_earning.csv")

In [10]:
import pandas as pd

# Earnings 데이터 추가 분석
if 'earnings_df' in locals() and not earnings_df.empty:
    # EPS 추정치와 실제 EPS의 차이 분석
    earnings_df['eps_difference'] = earnings_df['reported_eps'].astype(float) - earnings_df['eps_estimate'].astype(float)
    
    print("\nEPS 차이 통계:")
    display(earnings_df[['symbol', 'company', 'eps_estimate', 'reported_eps', 'eps_difference']]\
           .dropna()\
           .sort_values('eps_difference', ascending=False)\
           .head())

EPS 차이 통계:

Empty DataFrame
Columns: [symbol, company, eps_estimate, reported_eps, eps_difference]
Index: []

In [ ]:
# Economic 데이터 추가 분석
if 'economic_df' in locals() and not economic_df.empty:
    # 실제값과 시장 예상치의 차이가 큰 이벤트 찾기
    economic_df['actual'] = pd.to_numeric(economic_df['actual'], errors='coerce')
    economic_df['market_expectation'] = pd.to_numeric(economic_df['market_expectation'], errors='coerce')
    economic_df['surprise'] = economic_df['actual'] - economic_df['market_expectation']
    
    print("\n시장 예상치 대비 실제값 차이가 큰 이벤트:")
    display(economic_df[['event', 'country', 'actual', 'market_expectation', 'surprise']]\
           .dropna()\
           .sort_values('surprise', ascending=False)\
           .head())